### ISSUE TITLE
MetaFunPrimer input files  prepare

### ISSUE THREAD

**Issue by aiqubo** [jialiu232/COVID-19_primers#1]
I also want to use MetaFunPrimer to design virus primer, but I don't know prepare input files, Could you please tell me, How do I prepare these file which Like in the example , such as "/sample_metagenomes" and "rpoB_sample_data".
thank you very much

**Comment by jialiu232** [comment]
`rpoB_sample_data` are supposed to be a fasta file of amino acid sequences, a fasta file of corresponding nucleotide sequences, and a mapping file that contains amino acid accession number as the first column and the corresponding nucleotide accession number as the second column. `/sample_metagenomes` is supposed to be a directory that contains metagenome files that used to specify and identify genes of interest. You can find more information in this tutorial `https://metafunprimer.readthedocs.io/en/latest/Tutorial.html`

**Comment by aiqubo** [comment]
Thank you for your feedback .
It's very useful to me

qubo
